PlasmaPro/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('plasmaapp.urls'))
]

plasmaapp/urls.py
from django.contrib.auth import logout
from django.urls import path

from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.home,name='home'),
    path('acceptor/',views.acceptor,name='acceptor'),
    path('donator/',views.donator,name='donator'),
    path('admin1/',views.admin1,name='admin1'),
    path('admin1/editaccept/<username>',views.editaccept,name='editaccept'),
    # path('editaccept/sendmail/<username>',views.mailAppointment,name='mailit'),
    # path('admin1/editdoaner/<id>',views.editdoaner,name='editdoaner'),
    path('SignUp/',views.signuppage,name='signup'),
    path('login/',views.loginpage,name='loginpage'),
    path('logout/',views.logoutpage,name='logout'),
    path('customer/',views.customerpage,name='customerpage'),
    path('customer/formfill',views.formfill,name='formfill'),
    
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name="password_reset.html"),name='reset_password'),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"),name='password_reset_done'),
    path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name="reset_token.html"),name='password_reset_confirm'),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name="reset_success.html"),name='password_reset_complete'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

plasmaapp/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.enums import Choices
from django.contrib.auth.models import User
# Create your models here.

class Donate(models.Model):
    name=models.CharField( 'Name of Donar',max_length=100,null=False)
    address=models.CharField('Address',max_length=200,null=False)
    phoneno=models.CharField('Phone Number',max_length=10,null=False)
    age=models.IntegerField('Age',null=False)
    GENDER=(('M','Male'),
    ('F','Female'),
    ('T','Trans'))
    gender=models.CharField('Gender',max_length=1,choices=GENDER,null=False)
    BLOODGROUP=(
    ('A+','A+'),
    ('A-','A-'),
    ('O+','O+'),
    ('O-','O-'),
    ('B+','B+'),
    ('B-','B-'),
    ('AB-','AB-'),
    ('AB+','AB+')
    )
    bloodgroup=models.CharField('Blood Group',max_length=3,choices=BLOODGROUP,null=False)
    dayofdonate=models.DateField('Day of Donating',null=True,blank=True)
    STATUS=(
    ('Pending','Pending'),
    ('Accepted','Accepted'),
    ('Donated','Donated'),
    ('Rejected','Rejected')
    )
    status=models.CharField('Status',choices=STATUS,default='Pending',max_length=20,null=True,blank=True)
    def __str__(self):
        return self.name

class Accept(models.Model):
    name=models.CharField( max_length=100,null=False)
    address=models.CharField('Address',max_length=200,null=False)
    phoneno=models.CharField('Phone Number',max_length=10,null=False)
    age=models.IntegerField('Age',null=False)
    GENDER=(('M','Male'),
    ('F','Female'),
    ('T','Trans'))
    gender=models.CharField('Gender',max_length=1,choices=GENDER,null=False)
    BLOODGROUP=(
    ('A+','A+'),
    ('A-','A-'),
    ('O+','O+'),
    ('O-','O-'),
    ('B+','B+'),
    ('B-','B-'),
    ('AB-','AB-'),
    ('AB+','AB+')
    )
    bloodgroup=models.CharField('Blood Group',max_length=3,choices=BLOODGROUP,null=False)
    dayofaccept=models.DateField('Day of Accepting',null=True,blank=True)
    STATUS=(
    ('Pending','Pending'),
    ('Accepted','Accepted'),
    ('GotIt','GotIt'),
    ('Rejected','Rejected')
    )
    status=models.CharField('Status',choices=STATUS,default='Pending', max_length=20,null=True,blank=True)
    def __str__(self):
        return self.name

class Customer(models.Model):
    user=models.OneToOneField(User,null=True,blank=True,on_delete=CASCADE)
    username=models.CharField('Username',max_length=200,primary_key=True)
    name=models.CharField( max_length=100,null=True,blank=True)
    email=models.EmailField('Email',null=True,blank=True,default='abc@gmail.com')
    address=models.CharField('Address',max_length=200,null=True,blank=True)
    phoneno=models.CharField('Phone Number',max_length=10,null=True,blank=True)
    age=models.IntegerField('Age',null=True,blank=True)
    prescription=models.ImageField(null=True,blank=True)
    GENDER=(('M','Male'),
    ('F','Female'),
    ('T','Trans'))
    gender=models.CharField('Gender',max_length=1,choices=GENDER,null=True,blank=True)
    BLOODGROUP=(
    ('A+','A+'),
    ('A-','A-'),
    ('O+','O+'),
    ('O-','O-'),
    ('B+','B+'),
    ('B-','B-'),
    ('AB-','AB-'),
    ('AB+','AB+')
    )
    bloodgroup=models.CharField('Blood Group',max_length=3,choices=BLOODGROUP,null=True,blank=True)
    dayofaccept=models.DateField('Day of Accepting',null=True,blank=True)
    NEED=(('None','None'),
        ('Acceptor','Acceptor'),
    ('Donator','Donator'),)
    need=models.CharField('Need',choices=NEED,default='None',null=True,blank=True,max_length=20)
    STATUS=(
    ('Pending','Pending'),
    ('Accepted','Accepted'),
    ('GotIt','GotIt'),
    ('Rejected','Rejected')
    )
    status=models.CharField('Status',choices=STATUS,default='Pending', max_length=20,null=True,blank=True)
    

plasmaapp/forms.py
from django import forms
from django.forms import fields
from .models import Accept,Donate,Customer
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm






class SignUpform(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1','password2']











class DateInput(forms.DateInput):
    input_type = 'date'
class AcceptorForm(forms.ModelForm):
    class Meta:
        model=Accept
        fields = ['name','address','phoneno','age','gender','bloodgroup','dayofaccept','status']
        widgets={
            'dayofaccept':DateInput()
        }
        
class DonatorForm(forms.ModelForm):
    class Meta:
        model=Donate
        fields=['name','address','phoneno','age','gender','bloodgroup','dayofdonate','status']
        widgets={
            'dayofdonate':DateInput()
        }


class CustomerForm(forms.ModelForm):
    class Meta:
        model=Customer
        fields=['name','address','phoneno','age','gender','bloodgroup','dayofaccept','need','status','prescription']
        widgets={
            'dayofaccept':DateInput()
        }

plasmaapp/views.py
from django.shortcuts import redirect, render
from .forms import AcceptorForm,DonatorForm,CustomerForm,SignUpform
from .models import Accept,Donate,Customer
# Create your views here.
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .decorators import un_authenticated,allowed_user
from django.contrib.auth.models import Group
from django.contrib import messages
import datetime
from django.core.mail import BadHeaderError, send_mail

# @un_authenticated
# def signuppage(request):
    
#     form=UserCreationForm()
#     if request.method=='POST':
#         form=UserCreationForm(request.POST)
#         if form.is_valid():
#             user=form.save()
#             username=request.POST.get('username')
#             print(username)
            
#             group=Group.objects.get(name='customer')
#             user.groups.add(group)
#             Customer.objects.create(
#                 user=user,
#                 username=username,
#                 dayofaccept=datetime.date.today(),
#             )
#             return redirect(loginpage)
#         else:
#             for msg in form.error_messages:
#                 messages.error(request, f"{msg}: {form.error_messages[msg]}")
#                 print(msg)
#     context={
#         'form':form
#     }
#     return render(request,'signuppage.html',context)




@un_authenticated
def signuppage(request):
    
    form=SignUpform()
    if request.method=='POST':
        form=SignUpform(request.POST)
        if form.is_valid():
            user=form.save()
            username=request.POST.get('username')
            email=request.POST.get('email')
            print(username)
            
            group=Group.objects.get(name='customer')
            user.groups.add(group)
            Customer.objects.create(
                user=user,
                username=username,
                dayofaccept=datetime.date.today(),
                email=email
            )
            return redirect(loginpage)
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")
                print(msg)
    context={
        'form':form
    }
    return render(request,'signuppage.html',context)

















@un_authenticated
def loginpage(request):
    
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        
        user=authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect('home')
        else :
            print('wrong Password')
    return render(request,'loginpage.html',{})


def logoutpage(request):
    logout(request)
    return redirect('home')

@login_required(login_url='loginpage')
@allowed_user(allowedroles=['customer'])
def home(request):
    user=request.user
    noofdonate1=Customer.objects.filter(need='Donator')
    noofdonate=0
    noofaccept=0
    # bloodgrpPresent=[]
    # bloodpresentApt=0
    # bloodpresentAng=0
    # bloodpresentOpt=0
    # bloodpresentOng=0
    # bloodpresentABpt=0
    # bloodpresentABng=0
    # bloodpresentBpt=0
    # bloodpresentBng=0
    for i in noofdonate1:
        if i.status=='GotIt':
            noofdonate+=1
            

    noofaccept1=Customer.objects.filter(need='Acceptor')
    for i in noofaccept1:
        if i.status=='GotIt':
            noofaccept+=1

    context={
        'user':user,
        'noofdonate':noofdonate,
        'noofaccept':noofaccept
    }

    return render(request,'home.html',context)

@login_required(login_url='loginpage')
def acceptor(request):
    form=AcceptorForm()
    if request.method=='POST':
        form=AcceptorForm(request.POST)
        form.save()
        return redirect('home')
    context={
        'form':form
    }
    return render(request,'acceptor.html',context)
@login_required(login_url='loginpage')
def donator(request):
    form=DonatorForm()
    if request.method=='POST':
        form=DonatorForm(request.POST)
        form.save()
        return redirect('home')
    context={
        'form':form
    }
    return render(request,'donator.html',context)










@login_required(login_url='loginpage')
@allowed_user(allowedroles=['customer'])
def customerpage(request):
    id=request.user
    instance=Customer.objects.get(username=id)
    form=CustomerForm(instance=instance)
    need=instance.need
    status=instance.status
    date=instance.dayofaccept
    if request.method=='POST':
        
        form=CustomerForm(request.POST,request.FILES,instance=instance)
        form.save()
        return redirect('customerpage')
    context={
        'form':form,
        'need':need,
        'status':status,
        'date':date
    }
    return render(request,'customerpage.html',context)



@login_required(login_url='loginpage')
@allowed_user(allowedroles=['customer'])

def formfill(request):
    username=request.user
    instance=Customer.objects.get(username=username)
    form=CustomerForm(instance=instance)
    if request.method=='POST':
        form=CustomerForm(request.POST,request.FILES,instance=instance)
        if form.is_valid():
            form.save()
            print('hii')
            return redirect('customerpage')
        else:
            print('Error bro')
    context={
        'form':form
    }
    return render (request,'formfill.html',context)













@login_required(login_url='loginpage')
@allowed_user(allowedroles=['admin'])
def admin1(request):
    
        
    instanceAccept=Accept.objects.filter(status='Pending')
    instanceAcceptall=Accept.objects.all()
    instanceDonate=Donate.objects.filter(status='Pending')
    instanceDonateall=Donate.objects.all()
    instanceCustomerall=Customer.objects.all()
    

    context={
        'PendingAcceptor':instanceAccept,
        'AllAcceptor':instanceAcceptall,
        'PendingDonator':instanceDonate,
        'AllDoaner':instanceDonateall,
        'AllCustomer':instanceCustomerall
    }
    return render(request,'admin.html',context)

@login_required(login_url='loginpage')
@allowed_user(allowedroles=['admin'])
def editaccept(request,username):
    isinstance=Customer.objects.get(username=username)
    print(isinstance.name)
    form1=CustomerForm(instance=isinstance)
    if request.method=='POST':
        form1=CustomerForm(request.POST,request.FILES,instance=isinstance)
        print(form1)
        # # form=request.POST.get('status')
        # isinstance.status=form1.status
        # isinstance.dayofaccept=()
        # # if form is not 'Pending':
        # #     print('hii')
        # #     date=None
        # #     date=request.POST.get('date')
        # #     print(date)
        # #     if date is not None:
        # isinstance.dayofaccept=form1.dayofaccept
        
        
        form1.save()
        instance=Customer.objects.get(username=username)
        status=instance.status
        message=''
        dt=instance.dayofaccept
        month=str(dt.month)
        year=str(dt.year)
        day=str(dt.day)
        # print(type(str(dt.month)))
        
        if not status=='Pending':
            subject='Staus '+instance.status
            if status =='Accepted':
                dayofaccept=instance.dayofaccept
                message='Hii '+instance.name+'\nYour request as '+instance.need+' has been approved!'+'\n Date of Appointment is '+day+'-'+month+'-'+year+'\nThank You'
            elif status=='GotIt':
                message='Hii '+instance.name+'\nThank You using our services'+'\nStay Safe Stay Happy'+'\nThank You'
            else:
                message='Hii '+instance.name+'\nSorry Due to certain reasons your request is rejected :('+'\nPlease fill the form correctly'+'\nThank You'
            send_mail(subject, message, 'ascsingh500@gmail.com',[instance.email])
            return redirect(admin1)
    context={
        'customer':isinstance,
        'form':form1,
        
    }
    
    return render(request,'adminedit.html',context)

# @login_required(login_url='loginpage')
# @allowed_user(allowedroles=['admin'])
# def mailAppointment(request,username):
    
#     instance=Customer.objects.get(username=username)
#     status=instance.status
#     message=''
#     if not status=='Pending':
#         subject='Staus '+instance.status
#         if status =='Accepted':
#             message='Hii '+instance.name+'\nYour request as '+instance.need+' has been approved!'+'\n Date of Appointment is '+instance.dayofaccept+'\nThank You'
#         elif status=='GotIt':
#             message='Hii '+instance.name+'\nThank You using our services'+'\nStay Safe Stay Happy'+'\nThank You'
#         else:
#             message='Hii '+instance.name+'\nSorry Due to certain reasons your request is rejected :('+'\nPlease fill the form correctly'+'\nThank You'
#         send_mail(subject, message, ['techakash2000@gmail.com'])
#         return redirect(admin1)
#     return redirect('admine')
    

        

plasmaapp/templates/acceptor.html
<h1>Acceptor</h1>

<form action="" method="POST">
    {%csrf_token%}
    <div class="name"><span class="lable"> Name : </span>{{form.name}}</div>
    <div class="address"><span class="lable"> Address : </span>{{form.address}}</div>
    <div class="phoneno"><span class="lable"> Phone No. : </span>{{form.phoneno}}</div>
    <div class="age"><span class="lable"> Age : </span>{{form.age}}</div>
    <div class="gender"><span class="lable"> Gender : </span>{{form.gender}}</div>
    <div class="bloopgroup"><span class="lable"> Blood Group : </span>{{form.bloodgroup}}</div>
    



   
    <input type="submit">
</form>

plasmaapp/templates/adminedit.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>Edit Status</title>
    <style>
      .container{
        text-align: center;
      }
      h1{
        font-size: 45px;
        margin: 2% auto;
      }
      table{
        font-size: 18px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>{{customer.need}} Details</h1>
      <table class="table">
        <tr>
            <td>
                Name :
            </td>
            <td>{{customer.name}}</td>
        </tr>
       
        <tr>
         <td>

             Blood Group :
         </td>
         <td>{{customer.bloodgroup}}</td>
        </tr>
        
        <tr>
         <td>

             Age :
         </td>
         <td>{{customer.age}}</td>
        </tr>
        <tr>
            <td>Gender :</td>
            <td>{{customer.gender}}</td>
        </tr>
        <tr>
            <td>Phone Number : </td>
            <td> {{customer.phoneno}}</td>
        </tr>
        <tr>
          <td>Address :</td>
          <td>
            {{customer.address}}
          </td>
        </tr>
        <tr>
          <td>Email :</td>
          <td>
            {{customer.email}}
          </td>
        </tr>
        <tr>
          <td>Present Status :</td>
          <td>{{customer.status}}</td>
        </tr>
       
        <tr>
          <td>Date Given :</td>
          <td>{{customer.dayofaccept}}</td>
        </tr>
        <form action="" method="POST">{%csrf_token%}
          <div style="display: none;">

            {{form.name}}
            {{form.age}}
            {{form.phoneno}}
            {{form.address}}
            {{form.bloodgroup}}
            {{form.need}}
            {{form.email}}
            
          </div>
          <tr>
            
              <td>
                Edit Status :
              </td>
              <td>
                <!-- <select id="status" name="status" value="{{customer.status}}">
                  <option value="Pending">Pending</option>
                  <option value="Accepted"selected>Accepted</option>
                  <option value="GotIt">GotIt</option>
                  <option value="Rejected">Rejected</option>
                </select> -->
                {{form.status}}
              </td>
            </tr>
            <tr>
              <td>
                change Date :
              </td>
              <td>
                <!-- <input type="date" name="date" class="mydate" > -->
                {% comment %} <input type="date" name="dayofaccept" value="{{customer.dayofaccept}}" id="id_dayofaccept" Required> {% endcomment %}
                 {{form.dayofaccept }}
              </td>
              
              
            </tr>
            <tr>
            <td> Prescription Uploaded</td>
            <td>{{form.prescription}}</td>
            </tr>

            <tr>
              <td>
                <a href="{%url 'admin1'%}"><button class="btn btn-danger">Cancel And Go Back</button></a>
                
              </td>
              <td>
                <input type="submit" class="btn btn-success"value="Save Changes">

              </td>
            </tr>
          
        </form>

       
        

        
    </table>
      <!-- <form action="" method="POST">{%csrf_token%}
        <label for="status" > Edit Status</label>
          <select id="status" name="status">
              <option value="Pending">Pending</option>
              <option value="Accepted">Accepted</option>
              <option value="GotIt">GotIt</option>
              <option value="Rejected">Rejected</option>
            </select>
            <input type="date" name="date">
            <input type="submit">
        
      </form> -->
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

   
  </body>
</html>

plasmaapp/templates/customerpage.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <style>
        .container{
            margin: 2% auto;
            text-align: center;
           
           color: white;
           height: 500px;
           padding: 1%;

        }
        span{
            width: 300px;
        }
        .main{
            text-align: center;
            padding-top: 40px ;
            background-color: #65ca12;
            height: 500px;
        }
        #id_name{
            color: white;
            text-align: center;
            background-color: #65ca12;
            border: 2px solid green;
            border-radius: 15px;
            width: 250px;
            padding: 5px 10px;
        }
        #id_age{
            color: white;
            text-align: center;
            background-color: #65ca12;
            border: 2px solid green;
            border-radius: 15px;
            width: 250px;
            padding: 5px 10px;
        }
        #id_phoneno{
            color: white;
            text-align: center;
            background-color: #65ca12;
            border: 2px solid green;
            border-radius: 15px;
            width: 250px;
            padding: 5px 10px;
        }
        #id_address{
            color: white;
            text-align: center;
            background-color: #65ca12;
            border: 2px solid green;
            border-radius: 15px;
            width: 250px;
            padding: 5px 10px;
        }
        #id_gender{
            color: white;
            text-align: center;
            background-color: #65ca12;
            border: 2px solid green;
            border-radius: 15px;
            width: 250px;
            padding: 5px 10px;
        }
        .btn{
            color: white;
            text-align: center;
            background-color: #65ca12;
            border: 2px solid green;
            width: 250px;

        }
        .btn:hover{
            color: green;
            background-color: white;
        }
        .table{
            text-align: center;
        }
        .side{
            padding-top: 40px ;
            margin-right: 20px;
            background-color: #65ca12;
            height: 500px;
        }
        /* .vl{
            height: 600px;
            border: 1px solid white;
            position: absolute;
            top: 0;
            left: 495px;
        } */
        .navbar{
            background-color: #65ca12;
        }
        .nav-link{
            font-size: 20px;
            color: white;
        }
        .navbar-brand{
            color: white;
        }
        a:hover{
            color: green;
        }
    </style>
    <title>Hello, world!</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg ">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active mr-5">
              <a class="nav-link" href="{%url 'home'%}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item mr-4">
              <a class="nav-link" href="{%url 'logout'%}">Logout</a>
            </li>
            
          </ul>
        </div>
      </nav>
    <div class="container">

        
        <!-- <div class="vl"></div> -->
        <div class="row">
            <div class="col-4 side">
                {%if not need == "None" %}
                <h1>Status : {{status}}</h1>
                {%if  need == "Donator"%}
                <h3>You Are Awesome</h3>
                {% if  status == "Pending"%}
                  <!-- <p>Your are doing a really great work for your country your help will save someone life</p>  -->
                    <h4>Will take some time in verfication!</h4>
                    <h4>When ever the verfication finishes we will provide you dates where you can donate blood</h4>
               
                {%elif  status == "Accepted"%}
                <h4>Thanks For your Interest</h4>
                <h4>Your Blood Donation Appointment is fixed on {{date}}</h4>
                {%elif status == "GotIt"%}
                <h4>Thank You for donating Blood</h4>
                <h4>Take Care!</h4>
                {%else%}
                <h4>Your Request is Rejected due to some reasons</h4>
                <h4>Please fill the form with correct details</h4>

                {%  endif %}
                {%else%}
                <h3>You will be fine</h3>
                {% if  status == "Pending"%}
                  <!-- <p>Your are doing a really great work for your country your help will save someone life</p>  -->
                    <h4>Will take really short time in verfication!</h4>
                    <h4>Once the verfication finishes we will provide you dates where you can accept blood</h4>
               
                {%elif  status == "Accepted"%}
                <h4>Your Request is Accepted</h4>
                <h4>Your Appointment is fixed on {{date}}</h4>
                {%elif status == "GotIt"%}
                <h4>Get Well Soon!</h4>
                <h4>Take Care!</h4>
                {%else%}
                <h4>Your Request is Rejected due to some reasons</h4>
                <h4>Please fill the form with correct details</h4>
                <p>Fill the form to Donate/Accept Blood <a href="{%url 'formfill' %}">Go Ahead</a></p>

                {%  endif %}


                {%endif%}
                {%else%}
                <h2>If You are safe Fine Donate Blood to save someones life</h2>
                <h2>OR</h2>
                <h2>If You need blood </h2>
                <p>Fill the form to Donate/Accept Blood <a href="{%url 'formfill' %}">Go Ahead</a></p>
                {%endif%}




              
            </div>
            <div class="col-7 main">
                <h1>
                    Profile
                </h1>
                <form method="POST">{% csrf_token %}
                    
                    <table class="table">
                        <tr>
                            <td>
                                Name :
                            </td>
                            <td>
                                {{form.name}}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Age : 
                            </td>
                            <td>
                                {{form.age}}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Adddress : 
                            </td>
                            <td>
                                {{form.address}}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Phone Number : 
                            </td>
                            <td>
                                {{form.phoneno}}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Gender : 
                            </td>
                            <td>
                                {{form.gender}}
                            </td>
                        </tr>
                    </table>
                    <div style="display: none;">
                        {{form.dayofaccept}}
                        {{form.bloodgroup}}
                        {{form.status}}
                        {{form.need}}
                    </div>
                    <!-- <div class="name"> <span>Name :</span>{{form.name}}</div>
                    <div class="age"><span>Age : </span>{{form.age}}</div>
                    <div class="Address"><span>Adddress : </span>{{form.address}}</div>
                    <div class="phoneno"><span>Phone Number : </span>{{form.phoneno}}</div>
                    <div class="gender"><span>Gender : </span>{{form.gender}}</div>
                    <div class="bloodgrp"><span>Blood Group</span>{{form.bloodgrp}}</div> -->
        
        
                
                <input type="submit" value="Update" class="btn">
                </form>

            </div>
           
        </div>
    </div>

   
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

plasmaapp/templates/donator.html
<h1>Donator</h1>

<form action="" method="POST">{%csrf_token%}
    <div class="name"><span class="lable"> Name : </span>{{form.name}}</div>
    <div class="address"><span class="lable"> Address : </span>{{form.address}}</div>
    <div class="phoneno"><span class="lable"> Phone No. : </span>{{form.phoneno}}</div>
    <div class="age"><span class="lable"> Age : </span>{{form.age}}</div>
    <div class="gender"><span class="lable"> Gender : </span>{{form.gender}}</div>
    <div class="bloopgroup"><span class="lable"> Blood Group : </span>{{form.bloodgroup}}</div>
    <input type="submit">
</form>